name: 2 - Checkout Workflow
on: [ workflow_dispatch ]
jobs:
    Job-1:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5
            
            - name: List files
              run: ls -la