name: Variables and Secrets Workflow
on:
    workflow_dispatch
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Docker Build
              env:
                CONTAINER_REGISTRY: docker.io
                DOCKER_USERNAME: cj404
                IMAGE_NAME: python-kube-app
                TAG: v2
              run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:$TAG

            - name: Docker Login
              env:
                DOCKER_USERNAME: cj404
                DOCKER_PASSWORD: docker@strong1
              run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
              
            - name: Docker Publish
              env:
                CONTAINER_REGISTRY: docker.io
                IMAGE_NAME: python-kube-app
                DOCKER_USERNAME: cj404
              run: echo docker push ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest 
    # deploy:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Docker Run
    #           run:
    #         - name: 
