name: Matrix Strategy
on:
  push:
  workflow_dispatch: 
jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
        image: [hello-world, alpine]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Display Docker Info
        run: docker info
      - name: Run
        run: docker run ${{ matrix.image }}
